### ISSUE TITLE
add an example how to use inside views? 

### ISSUE THREAD

**Issue by samayo** [Holt59/cakephp-bootstrap3-helpers#14]
I am new to cake 2.x and I want to use this plugin, but aside from installing there is nothing much that tell you how to use this inside your views, it would be nice if you add an example.

**Comment by Holt59** [comment]
Hi,

The documentation is available from the CakePHP 3 repository: https://holt59.github.io/cakephp3-bootstrap-helpers/

Most of it is compatible with the CakePHP 2 version. Unfortunately, I do not really maintain this repository since the release of CakePHP 3, so I will not have time to add custom documentation.

**Comment by Holt59** [comment]
Also note that except for the `BootstrapModalHelper` and some minors new methods (e.g. `BootstrapHtmlHelper::icon` or options (e.g. `prepend` and `append` for `BootstrapFormHelper::input`), you can use standard CakePHP code with these helpers, I have made them such that switching from standard CakePHP should have no impact on your PHP code.

**Comment by samayo** [comment]
Thanks, I will look into it :+1:
